version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "8080:15672"
    volumes:
      - rmq-data:/var/lib/rabbitmq

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
volumes:
  rmq-data:
  db-data: